part-1-create-an-entry - Aaditya Desai
adesai47/code-journal pull request #5
Opened 2024-06-04 22:36 UTC by adesai47

![Recording 2024-06-04 at 15 34 30](https://github.com/adesai47/code-journal/assets/87247195/20566eda-71ea-4b1d-ae03-188e58317814)

2024-06-04 23:05 UTC, adesai47 commented
![Recording 2024-06-04 at 16 04 34](https://github.com/adesai47/code-journal/assets/87247195/3c6a9823-724b-4ede-8286-b2f88bc0614f)

2024-06-04 23:10 UTC, brandon-moy requested changes
Good start but there are changes I need to see with your styling and in your TypeScript. Once you have completed the changes, please add a new gif of you running the application and I would like to see mobile and desktop 👍

2024-06-04 23:10 UTC, brandon-moy commented on css/styles.css
> +
The Code Journal header is not centered in the wireframe images so it should not be aligned center here.

2024-06-04 23:10 UTC, brandon-moy commented on css/styles.css
> +
Your image is shrinking when you put an image in that is smaller than your placeholder but you want it to stay the same size as the preview. I think you're either using the wrong width here or you are missing width on the parent element.

2024-06-04 23:10 UTC, brandon-moy commented on index.html
> +          </div>
Your text area should have more height to it like in the example image

2024-06-04 23:10 UTC, brandon-moy commented on css/styles.css
> +}
Your button should be aligned with the right side of the container, yours is slightly away from the right side of the container.

2024-06-04 23:10 UTC, brandon-moy commented on css/styles.css
> +}
Your inputs are not lined up on the right side with the text area

2024-06-04 23:10 UTC, brandon-moy commented on ts/data.ts
>  };
We gave you a data object and you should have kept it. This is the data object you should have and you should update your data object and DataModel interface
```
let data = {
  view: 'entry-form',
  entries: [],
  editing: null,
  nextEntryId: 1,
};
```

2024-06-04 23:10 UTC, brandon-moy commented on ts/data.ts
> +
Where did you get this `Object.assign()` from? We can just use the assignment operator like we did in the `typescript-local-storage` exercise `data = JSON.parse(savedData)`

2024-06-04 23:10 UTC, brandon-moy commented on ts/main.ts
> +
If you need to query for elements, all of them should be global at the top of your page. This way, you query for them when the page loads. Currently you are running your query every time you submit the form which is a bit wasteful and will slow down your application.

2024-06-06 16:49 UTC, adesai47 commented
![Recording 2024-06-06 at 09 45 54](https://github.com/adesai47/code-journal/assets/87247195/55261e58-8bed-4649-a97e-cbaad8a0ff4f)

2024-06-06 17:01 UTC, brandon-moy requested changes
Great revisions! I have 2 more revisions for you but they should be pretty quick to fix 👍

2024-06-06 17:01 UTC, brandon-moy commented on ts/data.ts
> +  data.nextEntryId = parsedData.nextEntryId;
You can just override the entire data object here, you don't need to go property by property. You will need to update `data` to be a `let` variable instead of a `const` variable and then you can just assign `data = parsedData`

2024-06-06 17:01 UTC, brandon-moy commented on css/styles.css
> +  display: flex;
You don't need the max-width here. It's actually forcing your image to be smaller than what you want. I would just leave this with a `width: 100%` and remove the `max-width` and `height`

2024-06-06 17:19 UTC, brandon-moy approved these changes
Great job, approved!

2024-06-06 17:19 UTC, merged